### PR TITLE
feat: Create cross-platform releases with CGO enabled

### LINKED ISSUE #111: Create cross-platform releases with CGO enabled
We want a github action which will cross-compile the package when a new tag is pushed and create a github release with the artifacts. 

- The package uses cgo modules, so we must be able to cross-compile for other platforms. This is probably done most easily with docker containers.
- We may use goreleaser for this. I have an example goreleaser file already but it does not work for cross-compilation. However, we are not required to use goreleaser.
- We already have the start of a github workflow, `release.yml` which uses goreleaser. You will want to modify this.

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/claim #111 
/fixes #111

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
please review @poundifdef

**Comment by poundifdef** [comment]
Hi - have you run this? I get errors when I run the command `GOARCH=amd64 GOOS=windows go build -o myapp-windows-amd64.exe` locally.

**Comment by Bhavyajain21** [comment]
> Hi - have you run this? I get errors when I run the command `GOARCH=amd64 GOOS=windows go build -o myapp-windows-amd64.exe` locally.

What errors do you see?

**Comment by poundifdef** [comment]
You can see that the workflow fails on your own branch: https://github.com/Bhavyajain21/scratchdata/actions/runs/8269250339

If you're able to show an example where the workflow works without an error on your fork then let me know and I'll review.

**Comment by Bhavyajain21** [comment]
Sure, will get back

**Comment by Bhavyajain21** [comment]
triggered the run on my fork

https://github.com/Bhavyajain21/scratchdata/actions/runs/8270051429

**Comment by poundifdef** [comment]
The action you linked to  is not for release.yml, it's for a different github action. This is the workflow we're checking: https://github.com/Bhavyajain21/scratchdata/actions/workflows/release.yml

**Comment by poundifdef** [comment]
Hi - are you still interested in this bug? If not I'll go ahead and close the issue.

**Comment by poundifdef** [comment]
No problem. Thanks for trying!

**Pull request closed without merging**
